package concert;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import org.junit.Rule;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.junit.contrib.java.lang.system.StandardOutputStreamLog;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.AssertThrows;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

public class ConcertTest {

	Performance perf = new Woodstock();

	@Rule
	public final StandardOutputStreamLog log = new StandardOutputStreamLog();

	@Test
	public void performanceIsNotNullTest() {
		assertNotNull("koncert powinen być przygotowany", perf);
	}
	
	@Test
	public void performanceTest() {
		log.clear();
		perf.perform();
	    assertEquals(
	    		"Wyłączenie telefonów\r\n"
	    		+ "Zajęcie miejsc\r\n"
	    		+ "Koncert Woodstock...\r\n"
	    		+ "Brawa i oklaski!!!\r\n",	            
	            log.getLog());
	}
}
