package concert;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import org.junit.Rule;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.junit.contrib.java.lang.system.StandardOutputStreamLog;

public class ConcertTest {

	Performance perf = new Woodstock();
	Performance perf2 = new Woodstock2();


	@Rule
	public final StandardOutputStreamLog log = new StandardOutputStreamLog();

	@Test
	public void performanceIsNotNullTest() {
		assertNotNull("koncert powinen być przygotowany", perf);
	}
	
	@Test
	public void performanceTest() {
		perf.perform();
	    assertEquals(
	    		"Koncert Woodstock...\r\n",
	            log.getLog());
	}

	@Test
	public void perf2Test() {
		try {
			perf2.perform();
			assertTrue("Powinien polecieć wyjątek", false);
    	} catch (Throwable t) {
    		assertTrue(t instanceof RuntimeException);
    	    assertEquals(
    	    		"Koncert Woodstock 2 ...\r\n",
    	            log.getLog());
    	}
	    
	}
	
}
